stryker-config:
  solution: '../StarWarsProgressBarIssueTracker.sln'
  project: 'StarWarsProgressBarIssueTracker.Domain.csproj'
  mutation-level: 'Complete'
  additional-timeout: 3000
  thresholds:
    high: 85
    low: 60
    break: 50
