# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain .NET SDK updates
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"

  # Maintain dependencies for .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/server/src/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/server/src/StarWarsProgressBarIssueTracker.App"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/app/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"
