# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github\workflows\dotnet.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github\workflows\dotnet.yml'
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore server/src/StarWarsProgressBarIssueTracker.sln

    - name: Generate GitHub GraphQL client
      run: dotnet build server/src/StarWarsProgressBarIssueTracker.Infrastructure.GitHub/StarWarsProgressBarIssueTracker.Infrastructure.GitHub.csproj

    - name: Generate Gitlab GraphQL client
      run: dotnet build server/src/StarWarsProgressBarIssueTracker.Infrastructure.Gitlab/StarWarsProgressBarIssueTracker.Infrastructure.Gitlab.csproj

    - name: Build
      run: dotnet build server/src/StarWarsProgressBarIssueTracker.sln --no-restore

    - name: Test
      run: dotnet test server/src/StarWarsProgressBarIssueTracker.sln --no-build --verbosity q --logger "trx;LogFileName=Tests.trx" --results-directory "TestResults" --filter "TestCategory!=Error"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: TestResults
      if: ${{ always() }}
