name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 20 * * TUE'
  workflow_dispatch:

env:
  HUSKY: 0

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'main' # Checkout the develop branch instead of the default branch

    - name: Update .NET SDK
      uses: martincostello/update-dotnet-sdk@v3
      with:
        global-json-file: server/global.json
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message-prefix: "chore: "
